name: Firebase Deploy

on:
  push:
    branches:
      - main  # Cambia a la rama que uses (por ejemplo, master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'  # Usa la versión de Flutter que necesites

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web

      - name: Set up Firebase
        uses: w9jds/firebase-action@v2
        with:
          args: apps:sdkconfig --project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}